//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_AdsorptionDryer_History
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DayID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Run { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDryer_CondPre { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDryer_EvapPre { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDryer_InletPre { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDryer_OutPre { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_InOutValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_YSJ_A { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_JRQ_A { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_INT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_OutT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_LeakT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_ATowerT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_BTowerT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_HeatTowerMidT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_HeatTowerOutT { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CDyer_DewPoint { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Loss_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Heater_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Blower_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Purge_T { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Purge_P { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Purge_DP { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Inlet_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Outlet_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UPI { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Load_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RUN_Time { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RunTime_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Dry_Trap { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ValveK { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ValveG { get; set; }
    }
}
