//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_Centrifuge_Real
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DayID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Outlet_T { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Outlet_P { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RET_T1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RET_T2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RET_T3 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Accumulated_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Inlet_dp { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> C { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> InletIOpen { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DiscgargeOpen { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> T3Air { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> T3Pressure { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> HydraulicAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PrimaryAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TwoStageAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ThreeStageAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Oil_TemAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Load_TemAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Unload_TemAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Rphase_TemAir { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ePower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> eQ { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Run_Time { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PCE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DRE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ERE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UPI { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Rank { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Monthly_Rank { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Run { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Load { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RunTime_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Part_Load_Rat { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> standard_P { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> LossRatio { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Ret_Trap1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Ret_Trap2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Ret_Trap3 { get; set; }
    }
}
