//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_Factory_Statistics
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DayID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string YMDH { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Dewpoint { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SumPower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ProduceFlowStation { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ProduceFlowCentrifuge { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UseFlow { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PipelinePressure { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FlowLoss { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UPI { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> LossRatio { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_Rated_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_Rated_power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DRE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TCE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RUN_NUM { get; set; }
    }
}
