//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_Station_History
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DayID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Air_T { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Air_H { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Water_P { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Water_T { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Water_F { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_P { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line1_V { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line1_A { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line1_PF { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line1_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line2_V { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line2_A { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line2_PF { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line2_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RUN_NUM { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> REQ_NUM { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ePower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UPI { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PCE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DRE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ERE { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RunTime_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FLP { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PressureLoss { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Dewpoint { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_Rated_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UPI_Save { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Line_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Part_Load_Ratio { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RunTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Energy_Save { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Power_Save { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Energy_Save_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Power_Save_Rate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Energy_Save_Cost { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Power_Save_Cost { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CompressorPower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Loss_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Dryer_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Sum_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Main_Rated_power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ReleaseRate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> eQ_MainSum { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CentrifugeSumQ { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TCE { get; set; }
    }
}
