//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_ChartAlias
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string factoryId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string stationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AreaId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string factoryName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string stationName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AreaName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FieldName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string layuiTitle { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string layuiArea { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string layuiOffset { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string chartYUnit { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string chartXLegend { get; set; }
    }
}
