//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Data_Check
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FieldName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AreaID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ResMax { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ResMin { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public int DisplayOrder { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public float UpperLimit { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public float LowerLimit { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<float> BaseValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DataSource { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Unit { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    }
}
