//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Data_Exception_MeasureMeter
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableName1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FieldName1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AreaID1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string value1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableName2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FieldName2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EquipID2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AreaID2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string value2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OccurTime { get; set; }
    }
}
