//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Data_Exception_Sta
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FieldName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AbnormalValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> DataSource { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OccurTime { get; set; }
    }
}
