//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Factory
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Introduction { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Product { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AnnualOutput { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Latitude { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Longtitude { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Altitude { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Size { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ClientID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    }
}
