//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Instrument
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Rated_Q { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DesignPressure { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Rated_V { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Rated_A { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Rated_Power { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Dewpoint { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Manufacture { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string RunYear { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> StationID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ClientID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DateOfProductionTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string SerialNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ExFlangeSize { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ShapeSize { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Refrigerantype { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string AdsorbentType { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> FilterNum { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> GasConsumptionRate { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AreaID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PrimaryIntercoolerPower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SecondaryIntercoolerPower { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ThirdintercoolerPower { get; set; }
    }
}
