//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_MeasureMeter
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Code { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Variety { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string MeasurementRange { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string RunYear { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CalibrationTime { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Manufacture { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Location { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> InstrumentID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> AreaID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> FactoryID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ClientID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    }
}
