//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_Threshold
    {
    	/// <summary>
        /// 
        /// </summary>
        public short ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SetValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CurrentValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string classify { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Description { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string RealDescription { get; set; }
    }
}
