//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcHelperItems
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string EnumTag { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Tag { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Value { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Time { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Quality { get; set; }
    }
}
