//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLCBase
    {
    	/// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string SignName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string SignType { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<bool> PLCSignValue { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string SingAlias { get; set; }
    }
}
