//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Client
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Telephone { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string CompanyMail { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Contacts { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ContactsCellone { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ContactsMail { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string state { get; set; }
    }
}
