//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_Page
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ShowName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PageNameCN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PageNameEN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string URL { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ParentID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> SortN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string IconClass { get; set; }
    }
}
