//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_TableDictionary
    {
    	/// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableNameEN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string TableNameCN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ColumnNameEN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string ColumnNameCN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DicCode { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string DicCodeCN { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string IsDefault { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string IsMaintenance { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> SortNo { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Valid { get; set; }
    }
}
