//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SB_User
    {
    	/// <summary>
        /// 
        /// </summary>
        public System.Guid ID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Account { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string PassWord { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string UserType { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Sex { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string IDNo { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Cellphone { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public Nullable<int> ClientID { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    	/// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
    }
}
