//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    using Model;
    using Base;
    using IRepository;
      /// <summary>
      /// 负责每个数据表的数据操作
      /// </summary>
    public partial class BB_ThresholdRepository:BaseRepository<BB_Threshold>,IBB_ThresholdRepository
    {
       #region 针对此表的特殊操作写在此处
            
      #endregion
    } 
}
