//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface IAP_Centrifuge_RealServices:IBaseServices<AP_Centrifuge_Real>
    {
        #region 针对此表的特殊操作写在此处
        #region 大数据界面空压机服务接口
        /// <summary>
        /// 大数据界面，空压机能效开关数据
        /// </summary>
        /// <param name="currtime">当前时间</param>
        /// <param name="begtime">之前时间</param>
        /// <returns></returns>
        List<List<Model.ViewObject.CenSwitchStack_VO>> SwitchStackSer(DateTime currtime, DateTime begtime);


        /// <summary>
        /// 大数据界面空压机能效开关，upi不变，开关机变化
        /// </summary>
        /// <param name="currtime">当前时间</param>
        /// <param name="begtime">之前时间</param>
        /// <returns></returns>
        List<int> SwitchSer(DateTime currtime, DateTime begtime);
        #endregion




        #region 趋势分析空压机服务接口方法
        /// <summary>
        /// 趋势分析界面空压机所有数据
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="censtrlist">空压机标识id集合</param>
        /// <returns></returns>
        object TrendCentri(DateTime currtime, DateTime begtime, List<string> censtrlist);



        /// <summary>
        /// 趋势分析界面空压机所有数据实时刷新
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="censtrlist">空压机标识id集合</param>
        /// <returns></returns>
        object TrendCentriAjax(DateTime currtime, DateTime begtime, List<string> censtrlist);
        #endregion



        #region 统计分析空压机服务接口方法
        /// <summary>
        /// 统计分析，空压站压力功率图，实时表
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="sid"></param>
        /// <returns></returns>
        object StaMainpq(DateTime currtime, DateTime begtime, string sid);


        /// <summary>
        /// 空压机，统计分析产气量功率图，实时表
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="sidcid"></param>
        /// <returns></returns>
        object CentriProduceEpower(DateTime currtime, DateTime begtime, string sidcid);

        /// <summary>
        ///空压机，统计分析单耗放散率图，实时表
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="sidcid"></param>
        /// <returns></returns>
        object CentriUpiLoss(DateTime currtime, DateTime begtime, string sidcid);
        /// <summary>
        /// 空压机，统计分析压力功率图，实时表
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="sidcid"></param>
        /// <returns></returns>
        object CentriPEpower(DateTime currtime, DateTime begtime, string sidcid);

        /// <summary>
        /// 空压机，统计分析BOv开度放散率散点图，实时表
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="sidcid"></param>
        /// <returns></returns>
        object CentriBovLoss(DateTime currtime, DateTime begtime, string sidcid);
        #endregion
        #endregion
    }
}
