//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface IAP_AdsorptionDryer_RealServices:IBaseServices<AP_AdsorptionDryer_Real>
    {
        #region 针对此表的特殊操作写在此处
        /// <summary>
        /// 趋势分析干燥机实时
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="Drystrlist"></param>
        /// <returns></returns>
        object TrendDryer(DateTime currtime, DateTime begtime, List<string> Drystrlist);
        /// <summary>
        /// 趋势分析干燥机ajax
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="Drystrlist"></param>
        /// <returns></returns>
        object TrendDryerAjax(DateTime currtime, DateTime begtime, List<string> Drystrlist);
      #endregion
    } 
}
