//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface IAP_Centrifuge_StatisticsServices:IBaseServices<AP_Centrifuge_Statistics>
    {
        #region 针对此表的特殊操作写在此处
        List<Model.Stack> StackSer(DateTime currtime, DateTime begtime);
        /// <summary>
        /// 空压机统计upi放散率压力流量
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <returns></returns>
        object CenUpiLosspq(DateTime currtime, DateTime begtime);
        /// <summary>
        /// 空压机统计放散率图
        /// </summary>
        /// <param name="currtime"></param>
        /// <param name="begtime"></param>
        /// <param name="arr"></param>
        /// <returns></returns>
        List<decimal[]> CenlossSer(DateTime currtime, DateTime begtime, double[] arr);
        object CenPEpower(DateTime currtime, DateTime begtime);
      #endregion
    } 
}
