//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface IBB_StationServices:IBaseServices<BB_Station>
    {
        #region 针对此表的特殊操作写在此处
        /// <summary>
        /// 空压站信息表
        /// </summary>
        /// <param name="limit"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        object StationListJson(int limit, int page, string code);
        /// <summary>
        /// 添加业务模型显示
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Model.BussionObject.StationShow_BO ModiStation(int id);
        /// <summary>
        /// 更新模型
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        int ModiStation(Model.BussionObject.StationShow_BO model);
        /// <summary>
        /// 添加空压站
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        int AddStation(Model.BussionObject.StationShow_BO model);
      #endregion
    } 
}
