//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface IRE_SysRolePageServices:IBaseServices<RE_SysRolePage>
    {
        #region 针对此表的特殊操作写在此处
        /// <summary>
        /// 角色权限表
        /// </summary>
        /// <param name="Roleid"></param>
        /// <param name="page"></param>
        /// <param name="limit"></param>
        /// <returns></returns>
        object RolePage(int Roleid, int page, int limit,string showname);
        /// <summary>
        /// 角色权限删除
        /// </summary>
        /// <param name="roleid"></param>
        /// <param name="pageid"></param>
        /// <returns></returns>
        int RolePageDelete(int roleid, int pageid, int parentid);
        List<Model.ModelViews.MainPage_View> AddPageLayer(int roleid);
        int SavePage(List<int> model, int roleid);
      #endregion
    } 
}
