//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IServices
{
    using System;
    using System.Collections.Generic;
    
    using Base;
    using Model;
      /// <summary>
      /// 负责每个数据表的业务逻辑操作的约定
      /// </summary>
    public partial interface ISB_UserServices:IBaseServices<SB_User>
    {
        #region 针对此表的特殊操作写在此处
        object UserList(int limit, int page, string account, string name, string contact, string state);
        //修改人员信息模型
        /// <summary>
        /// 根据id查用户信息
        /// </summary>
        /// <param name="uid"></param>
        /// <returns></returns>
        Model.BussionObject.UserShow_BO ModiUser(Guid uid);
        /// <summary>
        /// 修改保存
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        int ModiUser(Model.BussionObject.UserShow_BO model);
        List<Model.SB_User> QueryAll();
        int AddUser(Model.BussionObject.UserShow_BO model);
        /// <summary>
        /// 验证用户重名
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        int ValidAccount(string account);
        /// <summary>
        /// 根据用户账号查用户信息
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        Model.BussionObject.UserShow_BO ShowUser(string account);
      #endregion
    } 
}
